# Generated by Django 5.0 on 2024-02-27 14:37

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh123456', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(default='Nepal ko Thau', max_length=100)),
                ('image', models.ImageField(default='category.jpg', upload_to=core.models.user_directory_path)),
                ('description', models.CharField(blank=True, default='This category is beautiful', max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='tour', unique=True)),
                ('title', models.CharField(default='Nepal', max_length=100)),
                ('image', models.ImageField(default='tour,jpg', upload_to=core.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='This ia a beautiful place', null=True)),
                ('short_description', models.TextField(blank=True, default='This place is an extraordinary', null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='tour.jpg', upload_to='tour-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_images', to='core.tour')),
            ],
            options={
                'verbose_name_plural': 'Tour Images',
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.tour')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tour Reviews',
            },
        ),
    ]
