# Generated by Django 5.0 on 2024-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name_plural': 'Tours'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
