# Generated by Django 5.0 on 2024-02-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tour_options_remove_tour_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRecommendation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_review', models.IntegerField()),
                ('review', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Tour Recommendations',
            },
        ),
    ]
